(dp1
S'info'
p2
VCopies the active control shape to the other selected controls
p3
sS'name'
p4
VCopy Controller Shape
p5
sS'tags'
p6
VMMTK
p7
sS'syntax'
p8
S'python'
p9
sS'command'
p10
Vfrom mmtk.rigging.shapeshifter import copy_shape; copy_shape()
p11
sS'id'
p12
S'376d01acdcaf08'
p13
sS'icon'
p14
Vcopy.svg
p15
s.