(dp1
S'info'
p2
VFix mop list fields
p3
sS'name'
p4
VFix MOP Fields
p5
sS'tags'
p6
VMMTK
p7
sS'syntax'
p8
S'python'
p9
sS'command'
p10
Vfrom mmtk.rigging.mop import fix_object_list_fields\u000afix_object_list_fields()
p11
sS'id'
p12
S'376d018b7b5b2a'
p13
sS'icon'
p14
Vmite.svg
p15
s.