(dp1
S'info'
p2
VReloads MMT
p3
sS'name'
p4
VReload MMT
p5
sS'tags'
p6
VMMT
p7
sS'syntax'
p8
S'python'
p9
sS'command'
p10
Vfrom mmt.common.reload import reload_mmt; reload_mmt()
p11
sS'id'
p12
S'392540e684b9a0L'
p13
sS'icon'
p14
Vrefresh.svg
p15
s.