(dp1
S'info'
p2
VSelect Binding Joints
p3
sS'name'
p4
VSelect Binding Joints
p5
sS'tags'
p6
V
sS'syntax'
p7
S'python'
p8
sS'command'
p9
Vfrom mmt.dag import select_binding_joints\u000a\u000a\u000aselect_binding_joints()
p10
sS'id'
p11
S'394ddbedaafcd0L'
p12
sS'icon'
p13
V
s.